name: deploy
on: [push]
jobs:
    start-with-actions:
        runs-on: ubuntu-latest
        steps:
            - run: echo "Das wurde von ${{github.actor}} gestartet"
            - name: Checkout
              uses: actions/checkout@v4 
            - run: mvn -v
            - run: docker -v
            - uses: actions/setup-java@v4
              with:
                distribution: 'temurin'
                java-version: '22'
            - run: java --version 
            - name: build this shit
              run: mvn package
    build-an-imiage:
        needs: start-with-actions
        runs-on: ubuntu-latest
        steps:
            - name: checkout
              uses: actions/checkout@v4
            - run: java --version
            - name: use mvn to build image
              run: mvn spring-boot:build-image